version: '3'
services:
  traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

  node-server-base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: elephantseed/whalephant-seed-base:latest
    command: npm start
    container_name: node-server-base

#  node-server:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      args:
#        - JSPM_GITHUB_AUTH_TOKEN=$JSPM_GITHUB_AUTH_TOKEN
#    image: elephantseed/whalephant-seed:latest
#    labels:
#      - "traefik.backend=machine-echo"
#      - "traefik.frontend.rule=Host:docker.nginx.node.com"
#    container_name: node-server-container
#    ports:
#      - 8000:8000
#      - 7000:7000
#      - 5858:5858
#    volumes:
#      - ./app:/home/sloppylopez/app
#      - nodemodules_app:/home/sloppylopez/app/node_modules
#      - jspm_packages_app:/home/sloppylopez/app/jspm_packages
#      - github_packages_app:/home/sloppylopez/app/jspm_packages/github
#      - npm_packages_app:/home/sloppylopez/app/jspm_packages/npm
#
#volumes:
#  nodemodules_app:
#  jspm_packages_app:
#  github_packages_app:
#  npm_packages_app: