version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-container
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./server/nginx/certs:/etc/nginx/certs
    links:
      - node-server:node-server

#  node-server-base:
#    build:
#      context: .
#      dockerfile: Dockerfile.base
#    image: elephantseed/whalephant-seed-base:latest
#    command: npm start
#    container_name: node-server-base-container
##    volumes:
##      - ./app:/home/elephantseed/app

  node-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - JSPM_GITHUB_AUTH_TOKEN=$JSPM_GITHUB_AUTH_TOKEN
    image: <%= userName %>/<%= appName %>:latest
    command: npm start
    container_name: node-server-container
    ports:
      - 8080:8080
      - 5858:5858
    volumes:
      - .:/home/<%= userName %>
      - ./app:/home/<%= userName %>/app
      - nodemodules_app:/home/<%= userName %>/app/node_modules
      - jspm_packages_app:/home/<%= userName %>/app/jspm_packages
      - github_packages_app:/home/<%= userName %>/app/jspm_packages/github
      - npm_packages_app:/home/<%= userName %>/app/jspm_packages/npm
    environment:
      - VIRTUAL_HOST=docker.nginx.node.com
      - VIRTUAL_PORT=8080

volumes:
  nodemodules_app:
  jspm_packages_app:
  github_packages_app:
  npm_packages_app: