version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-container
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./server/nginx/certs:/etc/nginx/certs
    links:
      - node-server:node-server

  node-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - JSPM_GITHUB_AUTH_TOKEN=$JSPM_GITHUB_AUTH_TOKEN
    image: sloppylopez/<%= appName %>:latest
    container_name: node-container
    ports:
      - 8080:8080
    volumes:
      - .:/home/<%= appName %>
      - ./nodemodules_app:/home/<%= appName %>/app/node_modules
      - ./jspm_packages_app:/home/<%= appName %>/app/jspm_packages
      - ./github_packages_app:/home/<%= appName %>/app/jspm_packages/github
      - ./npm_packages_app:/home/<%= appName %>/app/jspm_packages/npm
    environment:
      - VIRTUAL_HOST=whalephantseed.com
      - VIRTUAL_PORT=8080

volumes:
  nodemodules_server:
  nodemodules_app:
  jspm_packages_app:
  github_packages_app:
  npm_packages_app: